#!/usr/bin/env tsx
/**
 * All-in-One E2E Test Runner
 * 
 * This script:
 * 1. Auto-detects environment and fixes .env.e2e configuration
 * 2. Checks prerequisites
 * 3. Seeds test users
 * 4. Runs E2E tests
 */

import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import dotenv from 'dotenv'

const envE2EPath = path.resolve(process.cwd(), '.env.e2e')
const envPaths = [
  path.resolve(process.cwd(), '.env.local'),
  path.resolve(process.cwd(), '.env'),
  path.resolve(process.cwd(), 'env.local'),
  path.resolve(process.cwd(), 'env'),
]

console.log('🚀 Starting E2E test run...\n')

// Step 1: Auto-detect and fix configuration
const requiredVars = [
  'SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
]

// Detect cloud environment (more comprehensive)
const isCloudEnv = 
  process.env.CI === 'true' || 
  process.env.CURSOR === 'true' || 
  process.env.CODEX === 'true' || 
  process.env.DOCKER === 'true' ||
  process.env.GITHUB_ACTIONS === 'true' ||
  process.cwd().includes('/workspace') ||
  process.cwd().includes('/tmp') ||
  fs.existsSync('/.dockerenv') ||
  fs.existsSync('/.gitpod') ||
  (process.env.HOME && process.env.HOME.includes('codespace'))

// Load all potential env sources
const loadEnvFromFiles = () => {
  const envVars: Record<string, string> = {}
  for (const envPath of envPaths) {
    if (fs.existsSync(envPath)) {
      const loaded = dotenv.config({ path: envPath }).parsed || {}
      Object.assign(envVars, loaded)
    }
  }
  return envVars
}

// Get all available env vars (from files + process.env)
const fileEnvVars = loadEnvFromFiles()
const allEnvVars = { ...fileEnvVars, ...process.env }

// Check if we have all required vars from any source
const hasAllRequiredVars = requiredVars.every(v => allEnvVars[v])

let needsSync = false
let syncReason = ''

if (fs.existsSync(envE2EPath)) {
  const e2eEnv = dotenv.config({ path: envE2EPath }).parsed || {}
  const supabaseUrl = e2eEnv.SUPABASE_URL || e2eEnv.NEXT_PUBLIC_SUPABASE_URL || ''
  const isLocalhost = /^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(supabaseUrl)
  const allowRemote = e2eEnv.E2E_ALLOW_REMOTE_SUPABASE === 'true'
  
  // Check if we have localhost in cloud env (unless explicitly allowed)
  if (isLocalhost && isCloudEnv && !allowRemote) {
    needsSync = true
    syncReason = 'localhost in cloud environment'
  } 
  // Check if required vars are missing
  else if (!requiredVars.every(v => e2eEnv[v])) {
    needsSync = true
    syncReason = 'missing required variables'
  }
  // Check if we have better credentials available elsewhere
  else if (hasAllRequiredVars) {
    const remoteUrl = allEnvVars.SUPABASE_URL || allEnvVars.NEXT_PUBLIC_SUPABASE_URL || ''
    const isRemote = remoteUrl && !/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(remoteUrl)
    if (isRemote && isLocalhost) {
      needsSync = true
      syncReason = 'remote credentials available but .env.e2e has localhost'
    }
  }
} else {
  needsSync = true
  syncReason = '.env.e2e not found'
}

if (needsSync) {
  console.log(`📝 ${syncReason}, attempting to fix...`)
  
  if (!hasAllRequiredVars) {
    console.error('\n❌ Cannot find remote Supabase credentials!')
    console.error('   Required variables:')
    requiredVars.forEach(v => {
      const hasVar = !!allEnvVars[v]
      console.error(`     ${hasVar ? '✅' : '❌'} ${v}${hasVar ? ` (from ${fileEnvVars[v] ? 'file' : 'env'})` : ''}`)
    })
    console.error('\n   Options:')
    console.error('   1. Create a .env or .env.local file with remote Supabase credentials')
    console.error('   2. Set environment variables:')
    requiredVars.forEach(v => console.error(`      export ${v}=your-value`))
    console.error('   3. Run: pnpm e2e:diagnose (to see what\'s available)')
    process.exit(1)
  }
  
  // We have all required vars, create/update .env.e2e
  console.log('✅ Found all required Supabase credentials')
  
  // Determine source
  const source = envPaths.find(p => fs.existsSync(p)) 
    ? `file (${path.basename(envPaths.find(p => fs.existsSync(p))!)})`
    : 'environment variables'
  console.log(`   Source: ${source}`)
  
  // Create .env.e2e
  const lines = [
    '# E2E Test Environment Configuration',
    '# Auto-generated by pnpm e2e:all',
    `# Source: ${source}`,
    '',
    'E2E=true',
    '',
  ]
  
  const supabaseUrl = allEnvVars.SUPABASE_URL || allEnvVars.NEXT_PUBLIC_SUPABASE_URL || ''
  const isRemote = supabaseUrl && !/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(supabaseUrl)
  
  if (isRemote) {
    lines.push('# Remote Supabase detected - enabling remote mode')
    lines.push('E2E_ALLOW_REMOTE_SUPABASE=true')
    lines.push('')
  }
  
  lines.push('# Supabase Configuration')
  requiredVars.forEach(key => {
    const value = allEnvVars[key]
    if (value) {
      lines.push(`${key}=${value}`)
    }
  })
  
  // Preserve BASE_URL if set, otherwise use default
  if (allEnvVars.BASE_URL) {
    lines.push('')
    lines.push(`BASE_URL=${allEnvVars.BASE_URL}`)
  } else if (allEnvVars.E2E_BASE_URL) {
    lines.push('')
    lines.push(`BASE_URL=${allEnvVars.E2E_BASE_URL}`)
  } else {
    lines.push('')
    lines.push('BASE_URL=http://localhost:3000')
  }
  
  // Preserve E2E_SKIP_SEED if set
  if (allEnvVars.E2E_SKIP_SEED) {
    lines.push('')
    lines.push(`E2E_SKIP_SEED=${allEnvVars.E2E_SKIP_SEED}`)
  }
  
  fs.writeFileSync(envE2EPath, lines.join('\n') + '\n')
  console.log('✅ Updated .env.e2e')
  if (isRemote) {
    console.log('⚠️  Remote Supabase detected - E2E_ALLOW_REMOTE_SUPABASE=true set')
    console.log(`   Supabase URL: ${supabaseUrl}`)
  } else {
    console.log('ℹ️  Local Supabase detected')
  }
  console.log('')
}

// Step 2: Check prerequisites
console.log('\n🔍 Checking prerequisites...')
try {
  execSync('pnpm e2e:check', { stdio: 'inherit' })
} catch (error) {
  console.error('\n❌ Prerequisites check failed')
  console.error('   Fix the issues above before running tests')
  process.exit(1)
}

// Step 3: Seed test users (unless skipped)
if (process.env.E2E_SKIP_SEED !== 'true') {
  console.log('\n🌱 Seeding test users...')
  try {
    execSync('pnpm e2e:seed', { stdio: 'inherit' })
  } catch (error: any) {
    // Check if it's a connection error
    if (error.message?.includes('ECONNREFUSED') || error.message?.includes('connect')) {
      console.error('\n❌ Cannot connect to Supabase')
      console.error('   Make sure Supabase is running (pnpm db:start) or use a remote instance')
      console.error('   For remote Supabase, ensure E2E_ALLOW_REMOTE_SUPABASE=true in .env.e2e')
    } else {
      console.error('\n❌ Failed to seed test users')
    }
    process.exit(1)
  }
} else {
  console.log('\n⏭️  Skipping user seeding (E2E_SKIP_SEED=true)')
}

// Step 4: Run E2E tests
console.log('\n🧪 Running E2E tests...\n')

const testArgs = process.argv.slice(2).join(' ')
const testCommand = testArgs ? `pnpm e2e -- ${testArgs}` : 'pnpm e2e'

try {
  execSync(testCommand, { stdio: 'inherit' })
  console.log('\n✅ E2E tests completed successfully!')
} catch (error) {
  console.error('\n❌ E2E tests failed')
  process.exit(1)
}

