#!/usr/bin/env tsx
/**
 * Sync E2E Environment Variables
 * 
 * Copies Supabase-related environment variables from .env to .env.e2e
 * if .env.e2e doesn't exist or is missing required variables.
 */

import fs from 'node:fs'
import path from 'node:path'
import dotenv from 'dotenv'

// Check for .env in common locations
const envPaths = [
  path.resolve(process.cwd(), '.env.local'),
  path.resolve(process.cwd(), '.env'),
  path.resolve(process.cwd(), 'env.local'),
  path.resolve(process.cwd(), 'env'),
]

const envPath = envPaths.find(p => fs.existsSync(p))
const envE2EPath = path.resolve(process.cwd(), '.env.e2e')

// Required variables for E2E tests
const requiredVars = [
  'SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
]

// Check if required vars are already in process.env (might be set by shell/CI)
const hasRequiredVars = requiredVars.every(v => process.env[v])

if (!envPath && !hasRequiredVars) {
  console.error('❌ No .env file found. Checked:', envPaths.map(p => path.basename(p)).join(', '))
  console.error('   Make sure you have a .env or .env.local file with Supabase credentials')
  console.error('   Or set these environment variables:')
  requiredVars.forEach(v => console.error(`     - ${v}`))
  process.exit(1)
}

if (envPath) {
  console.log(`📄 Using ${path.basename(envPath)}`)
} else {
  console.log('📄 Using environment variables from process.env')
}

// Load .env (also check process.env for variables that might already be loaded)
const loadedEnv = envPath ? dotenv.config({ path: envPath }).parsed || {} : {}
const envVars = { ...loadedEnv, ...process.env }
const missingVars = requiredVars.filter(v => !envVars[v])

if (missingVars.length > 0) {
  console.error(`❌ Missing required variables in .env: ${missingVars.join(', ')}`)
  process.exit(1)
}

// Load existing .env.e2e if it exists
let existingE2E: Record<string, string> = {}
if (fs.existsSync(envE2EPath)) {
  existingE2E = dotenv.config({ path: envE2EPath }).parsed || {}
}

// Determine if we should allow remote Supabase
const supabaseUrl = envVars.SUPABASE_URL || envVars.NEXT_PUBLIC_SUPABASE_URL || ''
const isRemote = !/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(supabaseUrl)

// Build .env.e2e content
const lines: string[] = [
  '# E2E Test Environment Configuration',
  '# Auto-generated by scripts/e2e/sync-env.ts',
  '#',
  '# This file is synced from .env for E2E testing.',
  '# Edit .env and re-run: pnpm e2e:sync-env',
  '',
  '# E2E flag (required by Playwright)',
  'E2E=true',
  '',
]

if (isRemote) {
  lines.push('# Remote Supabase detected - enabling remote mode')
  lines.push('E2E_ALLOW_REMOTE_SUPABASE=true')
  lines.push('')
}

lines.push('# Supabase Configuration')
for (const key of requiredVars) {
  const value = envVars[key] || process.env[key]
  if (value) {
    lines.push(`${key}=${value}`)
  }
}

// Preserve other E2E-specific vars from existing .env.e2e
const e2eSpecificVars = ['BASE_URL', 'E2E_BASE_URL', 'E2E_SKIP_SEED']
for (const key of e2eSpecificVars) {
  if (existingE2E[key] && !envVars[key]) {
    lines.push('')
    lines.push(`# Preserved from existing .env.e2e`)
    lines.push(`${key}=${existingE2E[key]}`)
  }
}

// Write .env.e2e
fs.writeFileSync(envE2EPath, lines.join('\n') + '\n')

console.log('✅ Synced Supabase credentials from .env to .env.e2e')
if (isRemote) {
  console.log('⚠️  Remote Supabase detected - E2E_ALLOW_REMOTE_SUPABASE=true set')
} else {
  console.log('ℹ️  Local Supabase detected')
}

